# <center>Bài toán phân loại hoa Diên Vĩ</center>

## Các thư viện cần thiết 📑

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt  
import seaborn as sns
from scipy.stats import pearsonr 

import warnings 
warnings.filterwarnings('ignore')

## Đọc dữ liệu từ file .csv 🔃

In [2]:
data_frame = pd.read_csv("dataset/iris.csv")
data_frame

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

## Xử lý dữ liệu

In [3]:
# To check the Statistics of Data
data_frame.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [4]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [5]:
# Kiểm tra xem data có bản ghi nào null không.
data_frame.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [6]:
# Nếu có bản ghi nào bị trùng thì loại bỏ. 
data_frame.duplicated().sum()

0

In [7]:
data_frame.drop(columns=["Id"], inplace=True)
data_frame.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [8]:
# Đầu vào: Sepal length, Sepal Width, Petal length, and Petal Width
# Đầu ra: = Species

# X => Inputs -> SepalLenghtCm, SepalWidthCm, PetalLengthCm, PetalWidthCm
# Y => Ouput -> Species

features = ["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]
x = data_frame[features].values #Input
y = data_frame["Species"].values #Output

### Phân chia dữ liệu huấn luyện, dữ liệu test

In [9]:
# Phân chia dữ liệu huyến luyện và dữ liệu test. Trong đó tỷ lệ test là 1/5

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=0)

### Gán nhãn

In [10]:
# Label Encoder
# A technique is used in Machine Learning to convert categorical variables into numerical format.

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y)

LabelEncoder()

In [11]:
le.classes_

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [12]:
# Đánh index cho nhãn 
mapping = dict(zip(le.classes_, range(len(le.classes_))))
mapping

{'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2}

In [13]:
y = le.transform(y)

In [14]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [15]:
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

## Huấn luyện mô hình

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

### Hồi quy Logistic - Logistic Regression

In [17]:
model = LogisticRegression()
model.fit(X_train_scaled, y_train)

LogisticRegression()

In [18]:
model_prediction = model.predict(X_test_scaled)

In [19]:
accuracy_score(model_prediction, y_test)

1.0

### K-Nearest Neighbors

In [20]:
classi = KNeighborsClassifier(n_neighbors=3)
classi.fit(X_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=3)

In [21]:
classi_pred = classi.predict(X_test_scaled)

In [22]:
accuracy_score(y_test, classi_pred)

0.9333333333333333

### Support Vector Classifier (SVC)

In [23]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(X_train_scaled, y_train)

SVC()

In [24]:
svc_pred = svc.predict(X_test_scaled)

In [25]:
accuracy_score(y_test, svc_pred)

1.0

### Naive Bayes

In [26]:
from sklearn.naive_bayes import GaussianNB

naive_b = GaussianNB()
naive_b.fit(X_train_scaled, y_train)

GaussianNB()

In [27]:
naive_b_pred = naive_b.predict(X_test_scaled)

In [28]:
accuracy_score(y_test, naive_b_pred)

0.9333333333333333

## Đánh giá mô hình

In [29]:
confusion_matrix(y_test, model_prediction)

array([[3, 0, 0],
       [0, 8, 0],
       [0, 0, 4]], dtype=int64)

In [30]:
confusion_matrix(y_test, classi_pred)

array([[3, 0, 0],
       [0, 8, 0],
       [0, 1, 3]], dtype=int64)

In [31]:
confusion_matrix(y_test, svc_pred)

array([[3, 0, 0],
       [0, 8, 0],
       [0, 0, 4]], dtype=int64)

In [32]:
confusion_matrix(y_test, naive_b_pred)

array([[3, 0, 0],
       [0, 8, 0],
       [0, 1, 3]], dtype=int64)

## Kết hợp kết quả của các mô hình

In [33]:
results = pd.DataFrame({
    'Model' : ['Logistic Regression', 'SVM', 'KNN', 'Naive Bayes'],
    'Score' : [1.0, 1.0, 0.96, 0.96]
})

results_df = results.sort_values(by="Score", ascending=False)
results_df = results_df.set_index('Score')
results_df.head(9)

Model
Score                     
1.00   Logistic Regression
1.00                   SVM
0.96                   KNN
0.96           Naive Bayes

### Kết quả test của các mô hình dự đoán

In [34]:
model_prediction

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor'], dtype=object)

In [35]:
classi_pred

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor'], dtype=object)

In [36]:
svc_pred

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor'], dtype=object)

In [37]:
naive_b_pred

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor'], dtype='<U15')

## Triển khai

In [38]:
#### Lưu model sau khi được huấn luyện vào file .pkl

import pickle as pkl

pkl.dump(model, open('iris_model.pkl', 'wb'))
pkl.dump(scaler, open('iris_scaler.pkl', 'wb'))

In [1]:
with open('iris_scaler.pkl', 'rb') as scaler_file:
    data = pkl.load(scaler_file)

NameError: name 'pkl' is not defined

In [ ]:
type(data)

In [ ]:
sample_input = np.array([2.0, 5.8, 2.8, 4.2]).reshape(-1,4)
processdata = data.transform(sample_input)

In [ ]:
processdata

In [ ]:
with open('iris_model.pkl', 'rb') as model_file: 
    model_data = pkl.load(model_file)

model_predict = model_data.predict(processdata)

model_predict